#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG_VERY_VERBOSE 0
#define DEBUG_VERBOSE 0
#define DEBUG 0

#define HASHMAP_DEFAULT_CAPACITY 100003
#define QUEUE_DEFAULT_CAPACITY 100
#define QUEUE_DELAY 80
#define PARALLEL_PROBLEM_SIZE_THRESHOLD 5
#define PARALLEL_PROBLEM_MAX_THREADS 2

#define SCORE_UNDEFINED_SCORE 999999
#define SCORE_REGRESSION_PENALTY 5

#endif
