#ifndef CONFIG_H
#define CONFIG_H

//#define DEBUG_VERBOSE
#define DEBUG

#define ANALYZE_STATE_PRIORITY
#define PRUNE_DUPLICATE_STATES
#define ANALYZE_STATE_POSSIBLE

#define HASHMAP_DEFAULT_CAPACITY 93563 // prime
#define QUEUE_DEFAULT_CAPACITY 100

#define SCORE_UNDEFINED_SCORE 999999
#define SCORE_REGRESSION_PENALTY 5

#define SCORE score_min_of_all

#endif
